### ISSUE TITLE
Pass binary data feature in Lookup objects (at most 1) is broken

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/salesforce-component-v2#10]
**STR:** 
1. step1: any (simple trigger)
2. step2: salesforce-v2: Lookup objects (at most 1), input:
![image](https://user-images.githubusercontent.com/36419533/105469528-0e0aa200-5ca1-11eb-8e24-787891d438a2.png)

attachment id:  00P2R00001EMmXFUA1
3. Retrieve sample
**AR:** 
Error thrown:
`Error! 401 - {"type":"Buffer","data":[91,123,34,109,101,115,115,97,103,101,34,58,34,83,101,115,115,105,111,110,32,101,120,112,105,114,101,100,32,111,114,32,105,110,118,97,108,105,100,34,44,34,101,114,114,111,114,67,111,100,101,34,58,34,73,78,86,65,76,73,68,95,83,69,83,83,73,79,78,95,73,68,34,125,93]}`

logs:
```
StatusCodeError: 401 - {"type":"Buffer","data":[91,123,34,109,101,115,115,97,103,101,34,58,34,83,101,115,115,105,111,110,32,101,120,112,105,114,101,100,32,111,114,32,105,110,118,97,108,105,100,34,44,34,101,114,114,111,114,67,111,100,101,34,58,34,73,78,86,65,76,73,68,95,83,69,83,83,73,79,78,95,73,68,34,125,93]}
    at new StatusCodeError (/home/apprunner/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/apprunner/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/apprunner/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/apprunner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/apprunner/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/apprunner/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
**ER:** sample retrieved and binary data passed

**Comment by andrewreshitko** [comment]
will be fixed with https://github.com/elasticio/salesforce-component-v2/issues/18#issuecomment-1580222065
